[
  {
      "STT": 1,
      "ID": 1,
      "Name": "Taza Skin Clinic Thủ Đức",
      "BranchCode": "PVD",
      "Address": "800 Đường Phạm Văn Đồng, Hiệp Bình Chánh, Thủ Đức, Thành phố Hồ Chí Minh, Việt Nam",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "1900 2664",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TAZA",
      "ServerMail": "",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 2,
      "ID": 2,
      "Name": "Taza Skin Clinic Quận 10",
      "BranchCode": "C_T",
      "Address": "408 Cao Thắng, Phường 12, Quận 10, Hồ Chí Minh",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "1900 2664",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TAZA",
      "ServerMail": "",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 3,
      "ID": 3,
      "Name": "Taza Skin Clinic Gò Vấp",
      "BranchCode": "Q_T",
      "Address": "1014 Quang Trung, phường 8, Gò Vấp, Hồ Chí Minh",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "1900 2664",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TAZA",
      "ServerMail": "",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 4,
      "ID": 4,
      "Name": "Taza Skin Clinic Nha Trang",
      "BranchCode": "NHH",
      "Address": "STH 41.47 đường số 4 KĐT Lê Hồng Phong II, Phước Hải, Nha Trang, Khánh Hòa",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "1900 2664",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TAZA",
      "ServerMail": "",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 5,
      "ID": 6,
      "Name": "TAZA Skin Clinic Đà Nẵng",
      "BranchCode": "H_V",
      "Address": "69 Hàm Nghi, P. Thạc Gián, Q. Thanh Khê, Đà Nẵng",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "1900 2664",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TAZA",
      "ServerMail": "",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 6,
      "ID": 7,
      "Name": "Văn Phòng",
      "BranchCode": "VPC",
      "Address": "14-16 Bình Lợi, phường 13, Bình Thạnh, Thành phố Hồ Chí Minh, Việt Nam",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "1900 2664",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TAZA",
      "ServerMail": "timonaeducation@gmail.com",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 7,
      "ID": 14,
      "Name": "Timona Quận 10",
      "BranchCode": "T10",
      "Address": "334 Cao Thắng Phường 12 Quận 10 TP. Hồ Chí Minh",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "1900 2109",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TIMONA",
      "ServerMail": "timonaeducation@gmail.com",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 8,
      "ID": 15,
      "Name": "Timona Thủ Đức",
      "BranchCode": "TTD",
      "Address": "804 Phạm Văn Đồng, P. Hiệp Bình Chánh, Tp. Thủ Đức",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "1900 2109",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TIMONA",
      "ServerMail": "timonaeducation@gmail.com",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 9,
      "ID": 16,
      "Name": "Timona Gò Vấp",
      "BranchCode": "TGV",
      "Address": "1012-1014 Quang Trung, P. 8, Q. Gò Vấp",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "1900 2109",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TIMONA",
      "ServerMail": "timonaeducation@gmail.com",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 10,
      "ID": 17,
      "Name": "Timona Nha Trang",
      "BranchCode": "TNT",
      "Address": "Số S45/26, đường Thích Quảng Đức, P. Phước Hải",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "1900 2109",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TIMONA",
      "ServerMail": "timonaeducation@gmail.com",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 11,
      "ID": 18,
      "Name": "Timona Đà Nẵng",
      "BranchCode": "TDN",
      "Address": "77 Hàm Nghi, P. Thạc Gián, Q. Thanh Khê, Đà Nẵng",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "1900 2109",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TIMONA",
      "ServerMail": "timonaeducation@gmail.com",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 12,
      "ID": 19,
      "Name": "HR Taza Group",
      "BranchCode": "THR",
      "Address": "14 - 16 Bình lợi, Phường 13, Bình Thạnh, TP. Hồ Chí Minh",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "0935670135",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TAZA",
      "ServerMail": "",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 13,
      "ID": 20,
      "Name": "Timona Academy Hà Nội",
      "BranchCode": "THN",
      "Address": "Số 25 Nguyễn Quốc Trị, phường Trung Hòa, quận Cầu Giấy, Hà Nội",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "19002109",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 1,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TIMONA",
      "ServerMail": "",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  },
  {
      "STT": 14,
      "ID": 21,
      "Name": "Building Timona CMT8",
      "BranchCode": "TT8",
      "Address": "283/68+70 Cách Mạng Tháng 8, Phường 12, Quận 10, Thành phố Hồ Chí Minh",
      "Suggest_Location": "",
      "Target_Amount": 0,
      "Tel": "19002109",
      "IP": "",
      "TimeOpen": "08:00 Sáng - 20:00 Tối",
      "IsShowApp": 0,
      "EditButton": 0,
      "DeleteButton": 0,
      "SMSBrandName": "TIMONA",
      "ServerMail": "timonaeducation@gmail.com",
      "Represent": "",
      "RepresentPosition": "",
      "BranchAlias": ""
  }
]
